name: 'Jekyll Builder'
description: 'Build and deploy Jekyll site with academic plugins'
author: 'wsmoses'
inputs:
  branch:
    description: "What branch to push results to"
    required: true
branding:
  icon: 'arrow-up-circle'
  color: 'red'
runs:
  using: 'docker'
  image: 'docker://wsmoses/jekyll:latest'
  args:
    - ${{ inputs.branch }}
  env:
    JEKYLL_UID: 0
    JEKYLL_GID: 0
    JEKYLL_ROOTLESS: 1
